version: '3'
services:
  lambda:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - BUCKET_NAME=${BUCKET_NAME}
      - PRIVATE_KEY_SECRET_NAME=${PRIVATE_KEY_SECRET_NAME}
    ports:
      - "8080:8080"
